name: kendo
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
        # ... install modules before activating the license
      - name: Install NPM modules
        run: npm install

      - name: Activate Kendo UI License
        # Set working directory if the application is not in the repository root folder:
        # working-directory: 'ClientApp'
        run: npx kendo-ui-license activate
        env:
          KENDO_UI_LICENSE: ${{ secrets.KENDO_UI_LICENSE }}

      # ... run application build after license activation
      - name: Build Application
        run: npm run build